// 24本のアプリ設定（買い切り価格・説明）// + 将棋・チェス・オセロ・シニア脳トレ追加
export type AppConfig = {
  id: string;
  slug: string;
  title: string;
  titleEn: string;
  description: string;
  category: 'game' | 'tool' | 'wellness' | 'training';
  emoji: string;
  freeFeatures: string[];
  proFeatures: string[];
  price: number; // 円
  stripePriceId: string; // Stripe Price ID (本番時に設定)
  color: string; // Tailwind gradient
  releaseStatus: 'live' | 'soon';
};

export const APPS: AppConfig[] = [
  // ===== ゲーム系 =====
  {
    id: 'tetris',
    slug: 'tetris',
    title: 'テトリス',
    titleEn: 'Tetris',
    description: '定番ブロック落としゲーム',
    category: 'game',
    emoji: '🧱',
    freeFeatures: ['レベル1〜5', 'スタンダードテーマ', 'ハイスコア記録'],
    proFeatures: ['レベル1〜20', '10種類のテーマ', 'オンラインランキング', 'BGM 5種類'],
    price: 480,
    stripePriceId: 'price_1TmT84CnZYbd0wNBjZMg8Fym',
    color: 'from-blue-500 to-cyan-400',
    releaseStatus: 'live',
  },
  {
    id: 'sudoku',
    slug: 'sudoku',
    title: '数独',
    titleEn: 'Sudoku',
    description: '頭を使う数字パズル',
    category: 'game',
    emoji: '🔢',
    freeFeatures: ['易・普通 難易度', '無限生成', 'ヒント3回/日'],
    proFeatures: ['難・超難・地獄', '無制限ヒント', 'タイム記録', 'ペンシルメモ機能'],
    price: 480,
    stripePriceId: 'price_1TmT85CnZYbd0wNBuYWKt6jr',
    color: 'from-green-500 to-emerald-400',
    releaseStatus: 'live',
  },
  {
    id: 'minesweeper',
    slug: 'minesweeper',
    title: 'マインスイーパー',
    titleEn: 'Minesweeper',
    description: '地雷を避けて全マスを開放',
    category: 'game',
    emoji: '💣',
    freeFeatures: ['初級 (9×9)', '地雷10個', 'タイマー'],
    proFeatures: ['中級・上級・カスタム', '統計グラフ', 'タイムランキング', 'テーマ変更'],
    price: 380,
    stripePriceId: 'price_1TmT87CnZYbd0wNBA8Zuek3Z',
    color: 'from-red-500 to-orange-400',
    releaseStatus: 'live',
  },
  {
    id: '2048',
    slug: '2048',
    title: '2048',
    titleEn: '2048',
    description: '数字を合わせて2048を目指せ',
    category: 'game',
    emoji: '🔀',
    freeFeatures: ['4×4 グリッド', 'ベストスコア', 'アンドゥ3回'],
    proFeatures: ['5×5・6×6 グリッド', '無制限アンドゥ', 'カラーテーマ', 'AI自動プレイ観戦'],
    price: 380,
    stripePriceId: 'price_1TmT87CnZYbd0wNBPanLjwvT',
    color: 'from-yellow-500 to-amber-400',
    releaseStatus: 'live',
  },
  {
    id: 'snake',
    slug: 'snake',
    title: 'スネーク',
    titleEn: 'Snake',
    description: '伸びるヘビで餌を集めよう',
    category: 'game',
    emoji: '🐍',
    freeFeatures: ['スタンダードモード', 'ハイスコア', '3速度'],
    proFeatures: ['障害物モード・迷路モード', 'オンラインランキング', '5速度', 'カスタムスキン'],
    price: 380,
    stripePriceId: 'price_1TmT88CnZYbd0wNBuvYqBBC0',
    color: 'from-lime-500 to-green-400',
    releaseStatus: 'live',
  },
  {
    id: 'memory-card',
    slug: 'memory-card',
    title: '記憶カード',
    titleEn: 'Memory Card',
    description: '神経衰弱で記憶力を鍛える',
    category: 'game',
    emoji: '🃏',
    freeFeatures: ['6ペア (12枚)', '動物テーマ', 'タイム記録'],
    proFeatures: ['最大20ペア (40枚)', '10種テーマ', 'カスタム画像', '2人対戦モード'],
    price: 380,
    stripePriceId: 'price_1TmT89CnZYbd0wNByiJmV1FT',
    color: 'from-pink-500 to-rose-400',
    releaseStatus: 'live',
  },
  {
    id: 'breakout',
    slug: 'breakout',
    title: 'ブロック崩し',
    titleEn: 'Breakout',
    description: '古典的アクションゲーム',
    category: 'game',
    emoji: '🏓',
    freeFeatures: ['10ステージ', 'スタンダードボール', 'ハイスコア'],
    proFeatures: ['50ステージ', 'ボール・パドルカスタム', 'パワーアップアイテム', 'BGM 5種'],
    price: 480,
    stripePriceId: 'price_1TmT88CnZYbd0wNBlLlG1GzC',
    color: 'from-purple-500 to-violet-400',
    releaseStatus: 'live',
  },
  {
    id: 'slide-puzzle',
    slug: 'slide-puzzle',
    title: 'スライドパズル',
    titleEn: 'Slide Puzzle',
    description: '15パズル — 数字を並べ替えよう',
    category: 'game',
    emoji: '🔲',
    freeFeatures: ['3×3・4×4', 'タイム計測', '手数カウント'],
    proFeatures: ['5×5・6×6', 'オリジナル画像', 'ランキング', 'ヒント機能'],
    price: 380,
    stripePriceId: 'price_1TmT8ACnZYbd0wNB0Uhnfom5',
    color: 'from-teal-500 to-cyan-400',
    releaseStatus: 'live',
  },
  {
    id: 'rock-paper-scissors',
    slug: 'rock-paper-scissors',
    title: 'じゃんけん AI',
    titleEn: 'RPS AI',
    description: 'AIとじゃんけん対戦',
    category: 'game',
    emoji: '✂️',
    freeFeatures: ['ランダム AI', 'スコア記録', '10連戦'],
    proFeatures: ['学習型 AI (あなたのクセを読む)', 'vs 友達モード', '統計グラフ', '称号システム'],
    price: 480,
    stripePriceId: 'price_1TmT8ACnZYbd0wNBlhzjNvBn',
    color: 'from-indigo-500 to-blue-400',
    releaseStatus: 'live',
  },
  {
    id: 'typing',
    slug: 'typing',
    title: 'タイピング練習',
    titleEn: 'Typing',
    description: '日英タイピングスピードを鍛える',
    category: 'training',
    emoji: '⌨️',
    freeFeatures: ['日本語ひらがな', '基本単語200語', 'WPM計測'],
    proFeatures: ['英語・プログラミング・漢字', '単語1000語+', '成長グラフ', 'オリジナル文章登録'],
    price: 580,
    stripePriceId: 'price_1TmT8BCnZYbd0wNBBNw2PHwt',
    color: 'from-slate-600 to-gray-500',
    releaseStatus: 'live',
  },
  // ===== ツール・ウェルネス系 =====
  {
    id: 'pomodoro',
    slug: 'pomodoro',
    title: 'ポモドーロ',
    titleEn: 'Pomodoro',
    description: '25分集中 × 5分休憩タイマー',
    category: 'tool',
    emoji: '🍅',
    freeFeatures: ['基本タイマー', 'デスクトップ通知', 'セッション数カウント'],
    proFeatures: ['カスタム時間', '統計・週次グラフ', 'BGM 10種類', 'タスクリスト連携'],
    price: 580,
    stripePriceId: 'price_1TmT8DCnZYbd0wNBMgdikWsg',
    color: 'from-red-500 to-pink-400',
    releaseStatus: 'live',
  },
  {
    id: 'breathing',
    slug: 'breathing',
    title: '呼吸瞑想',
    titleEn: 'Breathing',
    description: '深呼吸でストレスを解消',
    category: 'wellness',
    emoji: '🌬️',
    freeFeatures: ['4-7-8 呼吸法', 'ガイドアニメーション', '3分セッション'],
    proFeatures: ['8種類の呼吸法', '最大30分', '環境音 8種', '記録・継続日数'],
    price: 580,
    stripePriceId: 'price_1TmT8ECnZYbd0wNBoyVOL9d8',
    color: 'from-sky-400 to-blue-300',
    releaseStatus: 'live',
  },
  {
    id: 'reaction',
    slug: 'reaction',
    title: '反応速度テスト',
    titleEn: 'Reaction',
    description: 'あなたの反応速度を計測',
    category: 'training',
    emoji: '⚡',
    freeFeatures: ['シンプルテスト', '5回計測・平均', '世界平均比較'],
    proFeatures: ['10種類のテスト', '30日間グラフ', '詳細統計', 'フレンドランキング'],
    price: 380,
    stripePriceId: 'price_1TmT8BCnZYbd0wNBsnpTEzZe',
    color: 'from-yellow-400 to-orange-400',
    releaseStatus: 'live',
  },
  {
    id: 'color-test',
    slug: 'color-test',
    title: '色彩テスト',
    titleEn: 'Color Test',
    description: 'あなたの色識別能力を測る',
    category: 'training',
    emoji: '🎨',
    freeFeatures: ['基本カラーテスト', 'スコア判定', '解説'],
    proFeatures: ['10種類のテスト', '色覚特性レポート', '詳細解析', 'PDF ダウンロード'],
    price: 480,
    stripePriceId: 'price_1TmT8GCnZYbd0wNBotZhzfmv',
    color: 'from-fuchsia-500 to-pink-400',
    releaseStatus: 'live',
  },
  {
    id: 'math-trainer',
    slug: 'math-trainer',
    title: '計算力トレーナー',
    titleEn: 'Math Trainer',
    description: '四則演算を高速でトレーニング',
    category: 'training',
    emoji: '🧮',
    freeFeatures: ['足し算・引き算', '初級・中級', '30問/日'],
    proFeatures: ['掛け算・割り算・分数', '上級・超級', '無制限', '成長グラフ'],
    price: 480,
    stripePriceId: 'price_1TmT8CCnZYbd0wNBwT90nYkt',
    color: 'from-emerald-500 to-teal-400',
    releaseStatus: 'live',
  },
  {
    id: 'kanji-quiz',
    slug: 'kanji-quiz',
    title: '漢字クイズ',
    titleEn: 'Kanji Quiz',
    description: '漢字の読み書きをマスター',
    category: 'training',
    emoji: '🀄',
    freeFeatures: ['N5・N4 レベル', '読み方クイズ', '毎日10問'],
    proFeatures: ['N1〜N5 全レベル', '書き取り・熟語', '苦手問題自動出題', '学習記録'],
    price: 680,
    stripePriceId: 'price_1TmT8CCnZYbd0wNBMB5k2dos',
    color: 'from-red-600 to-rose-500',
    releaseStatus: 'live',
  },
  {
    id: 'quote',
    slug: 'quote',
    title: '名言ジェネレーター',
    titleEn: 'Daily Quote',
    description: '毎日の言葉でモチベーションUP',
    category: 'wellness',
    emoji: '💭',
    freeFeatures: ['毎日1名言', '日本語のみ', 'シェア機能'],
    proFeatures: ['無制限生成', '日英・カテゴリ別', 'お気に入り保存', '壁紙ダウンロード'],
    price: 380,
    stripePriceId: 'price_1TmT8FCnZYbd0wNBURnDnz3h',
    color: 'from-violet-500 to-purple-400',
    releaseStatus: 'live',
  },
  {
    id: 'noise',
    slug: 'noise',
    title: '作業用 BGM',
    titleEn: 'Focus Noise',
    description: '集中できる環境音ミキサー',
    category: 'wellness',
    emoji: '🎧',
    freeFeatures: ['雨音・波音 2種', '音量調整', '30分タイマー'],
    proFeatures: ['15種類の環境音', '自由ミックス', '無制限時間', 'ポモドーロ連携'],
    price: 680,
    stripePriceId: 'price_1TmT8ECnZYbd0wNBH8721OzJ',
    color: 'from-blue-600 to-indigo-500',
    releaseStatus: 'live',
  },
  {
    id: 'color-palette',
    slug: 'color-palette',
    title: 'カラーパレット',
    titleEn: 'Color Palette',
    description: '美しい配色を瞬時に生成',
    category: 'tool',
    emoji: '🎨',
    freeFeatures: ['5色パレット生成', 'HEX コピー', '10種類の配色ルール'],
    proFeatures: ['8色・グラデーション', '保存・コレクション', 'CSS/SCSS エクスポート', 'Figma 連携'],
    price: 580,
    stripePriceId: 'price_1TmT8ECnZYbd0wNBWG0nlSK5',
    color: 'from-orange-500 to-yellow-400',
    releaseStatus: 'live',
  },
  {
    id: 'schedule',
    slug: 'schedule',
    title: '時間割メーカー',
    titleEn: 'Schedule Maker',
    description: '週間時間割を美しく作成',
    category: 'tool',
    emoji: '📅',
    freeFeatures: ['週間グリッド', '5色カラー', 'PNG 書き出し'],
    proFeatures: ['カスタムテンプレート', '無制限カラー', 'PDF 書き出し', 'Google Calendar 同期'],
    price: 580,
    stripePriceId: 'price_1TmT8GCnZYbd0wNBT1YzL7Uw',
    color: 'from-cyan-500 to-sky-400',
    releaseStatus: 'live',
  },
  // ===== ボードゲーム系（追加） =====
  {
    id: 'shogi',
    slug: 'shogi',
    title: '将棋',
    titleEn: 'Shogi',
    description: '日本の伝統ボードゲーム',
    category: 'game',
    emoji: '♟️',
    freeFeatures: ['初級 AI 対戦', '9×9 盤面', '駒の動き表示'],
    proFeatures: ['中級・上級・最強 AI', '棋譜記録・再生', 'ヒント機能', 'オンライン対戦'],
    price: 780,
    stripePriceId: 'price_1TmT85CnZYbd0wNB50ywPbVn',
    color: 'from-amber-700 to-yellow-600',
    releaseStatus: 'live',
  },
  {
    id: 'chess',
    slug: 'chess',
    title: 'チェス',
    titleEn: 'Chess',
    description: '世界標準のボードゲーム',
    category: 'game',
    emoji: '♛',
    freeFeatures: ['初級 AI 対戦', '8×8 盤面', '合法手ハイライト'],
    proFeatures: ['中級・上級・最強 AI', '棋譜 PGN 出力', 'Opening Book', 'オンライン対戦'],
    price: 780,
    stripePriceId: 'price_1TmT86CnZYbd0wNBwrhKeVQo',
    color: 'from-stone-600 to-gray-500',
    releaseStatus: 'live',
  },
  {
    id: 'othello',
    slug: 'othello',
    title: 'オセロ',
    titleEn: 'Othello',
    description: '黒と白のリバーシ対戦',
    category: 'game',
    emoji: '⚫',
    freeFeatures: ['初級 AI 対戦', '8×8 盤面', 'ヒント3回/局'],
    proFeatures: ['中級・上級・最強 AI', '詰めオセロ問題集', 'ランキング', 'テーマ変更'],
    price: 480,
    stripePriceId: 'price_1TmT86CnZYbd0wNBUdbCwMur',
    color: 'from-gray-700 to-gray-600',
    releaseStatus: 'live',
  },
  // ===== シニア向け =====
  {
    id: 'senior-brain',
    slug: 'senior-brain',
    title: 'シニア向け脳トレ',
    titleEn: 'Senior Brain',
    description: '認知機能を楽しく維持・向上',
    category: 'training',
    emoji: '🧠',
    freeFeatures: ['3種類の脳トレゲーム', '1日5問まで', 'スコア記録'],
    proFeatures: ['10種類の脳トレゲーム', '無制限プレイ', '認知機能レポート', '難易度AI自動調整', '30日間成長グラフ'],
    price: 680,
    stripePriceId: 'price_1TmT8HCnZYbd0wNBZHOeZ75T',
    color: 'from-green-600 to-teal-500',
    releaseStatus: 'live',
  },
];

export const getCategoryLabel = (cat: AppConfig['category']) => {
  const map = { game: 'ゲーム', tool: 'ツール', wellness: 'ウェルネス', training: 'トレーニング' };
  return map[cat];
};

export const getApp = (slug: string) => APPS.find(a => a.slug === slug);
